version: '3.3'
volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: bazhanovd/yamdb_final
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - ./static:/code/static
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.7
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx_default:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - 80:80