version: '3.3'
volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: bazhanovd/yamdb_final
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./static:/static
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.7
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx_default/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - 80:80